# Generated by Django 4.0.4 on 2022-04-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
